### ISSUE TITLE
解压大文件失败

### ISSUE THREAD

**Issue by xiabinbin** [wzv5/libpck#3]
请问超过解压后的文件夹3.4GB的时候就失败了

**Comment by wzv5** [comment]
有具体错误信息么

**Comment by xiabinbin** [comment]
解压到3.5GB就失败了，我用winpcck解压应该是7.8GB左右，烦请看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wzv5/libpck"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wzv5/libpck] 解压大文件失败 (Issue #3)





 
有具体错误信息么
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wzv5** [comment]
无法复现，请提供具体错误信息。

**Comment by xiabinbin** [comment]
能把您用的源码发一份给我吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月26日(周五) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wzv5/libpck] 解压大文件失败 (Issue #3)




 
无法复现，请提供具体错误信息。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wzv5** [comment]
我用的就是当前开源的，完全同步。
